### ISSUE TITLE
dev:wechat

### ISSUE THREAD

**Issue by denept** [kaola-fed/megalo#76] opened 2018-12-11 09:14 UTC
Vue packages version mismatch:

- vue@2.5.20
- vue-template-compiler@2.5.17

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the la
test.

**Comment by elcarim5efil** [comment] 2018-12-12 02:44
把 demo 里 vue 和 vue-template-compiler 去掉应该就好了，demo 工程对这两个包并没有依赖，多加了。谢谢反馈。

**Comment by elcarim5efil** [comment] 2018-12-12 02:50
Duplicate of #77

**Closed by elcarim5efil** 2018-12-12 02:50 UTC
Labels: duplicate
